# Generated by Django 5.0.6 on 2025-05-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='slug',
            field=models.SlugField(default=111, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
