# Generated by Django 5.0.6 on 2025-05-17 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_servicetype_slug_workshopprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.workshopprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.workshopprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopGallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workshop_gallery/')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.workshopprofile')),
            ],
        ),
    ]
