# Generated by Django 5.0.6 on 2025-05-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_aboutworker_addresses_workshopgallary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='slug',
        ),
    ]
