# Generated by Django 5.0.6 on 2025-05-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_workshopgallary_workshop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='img',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
