# Generated by Django 5.0.6 on 2025-05-26 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_remove_workshopprofile_image_workshopprofile_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
