# Generated by Django 5.0.6 on 2025-05-27 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_delete_addresses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshopprofile',
            options={'ordering': ['company_name'], 'verbose_name': 'Workshop Profile', 'verbose_name_plural': 'Workshop Profiles'},
        ),
        migrations.CreateModel(
            name='WorkshopRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.workshopprofile')),
            ],
        ),
    ]
