# Generated by Django 5.0.6 on 2025-06-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_mainservice_servicetype_maincategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopprofile',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
